// RNA adaptation of scripts/base_geometry_terms.mjs; SHA256 378d80f46df18c323487cc0a5bc22a09876ee5d95e6c78d4da5057a25ace81c9.
// Atom order is retained. Uracil has no thymine C7. O2 is distinct from ribose O2'.
// Scalar torsions are signed geometrical torsions, like x3DNA torsion2(),
// without torsion()'s covalent-distance gate (several survey terms are proxies).
const freezeDeep = value => { if (value && typeof value === 'object') { for (const child of Object.values(value)) freezeDeep(child); Object.freeze(value); } return value; };

export const BASE_ATOMS = freezeDeep({
  "A": [
    "N1",
    "C2",
    "N3",
    "C4",
    "C5",
    "C6",
    "N6",
    "N7",
    "C8",
    "N9",
    "C1'"
  ],
  "C": [
    "N1",
    "C2",
    "N3",
    "C4",
    "C5",
    "C6",
    "N4",
    "O2",
    "C1'"
  ],
  "G": [
    "N1",
    "C2",
    "N2",
    "N3",
    "C4",
    "C5",
    "C6",
    "O6",
    "N7",
    "C8",
    "N9",
    "C1'"
  ],
  "U": [
    "N1",
    "C2",
    "N3",
    "C4",
    "C5",
    "C6",
    "O2",
    "O4",
    "C1'"
  ]
});

export const TERM_REGISTRY = freezeDeep([
  {"term_id":"c_n1_c2_n3","display_name":"C.N1-C2-N3","survey_group":"base_internal_angles","value_type":"linear_angle","unit":"deg","observation_level":"residue","source_atom_pattern":["N1","C2","N3"],"allowed_bases":["C"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":false,"enabled":true,"notes":"Cytosine six-member ring internal angle. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"c_n1_c2_n3"},
  {"term_id":"c_c2_n3_c4","display_name":"C.C2-N3-C4","survey_group":"base_internal_angles","value_type":"linear_angle","unit":"deg","observation_level":"residue","source_atom_pattern":["C2","N3","C4"],"allowed_bases":["C"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":false,"enabled":true,"notes":"Cytosine six-member ring internal angle. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"c_c2_n3_c4"},
  {"term_id":"c_n3_c4_c5","display_name":"C.N3-C4-C5","survey_group":"base_internal_angles","value_type":"linear_angle","unit":"deg","observation_level":"residue","source_atom_pattern":["N3","C4","C5"],"allowed_bases":["C"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":false,"enabled":true,"notes":"Cytosine six-member ring internal angle. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"c_n3_c4_c5"},
  {"term_id":"c_c4_c5_c6","display_name":"C.C4-C5-C6","survey_group":"base_internal_angles","value_type":"linear_angle","unit":"deg","observation_level":"residue","source_atom_pattern":["C4","C5","C6"],"allowed_bases":["C"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":false,"enabled":true,"notes":"Cytosine six-member ring internal angle. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"c_c4_c5_c6"},
  {"term_id":"c_c5_c6_n1","display_name":"C.C5-C6-N1","survey_group":"base_internal_angles","value_type":"linear_angle","unit":"deg","observation_level":"residue","source_atom_pattern":["C5","C6","N1"],"allowed_bases":["C"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":false,"enabled":true,"notes":"Cytosine six-member ring internal angle. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"c_c5_c6_n1"},
  {"term_id":"c_c6_n1_c2","display_name":"C.C6-N1-C2","survey_group":"base_internal_angles","value_type":"linear_angle","unit":"deg","observation_level":"residue","source_atom_pattern":["C6","N1","C2"],"allowed_bases":["C"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":false,"enabled":true,"notes":"Cytosine six-member ring internal angle. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"c_c6_n1_c2"},
  {"term_id":"c_n3_c4_n4","display_name":"C.N3-C4-N4","survey_group":"base_internal_angles","value_type":"linear_angle","unit":"deg","observation_level":"residue","source_atom_pattern":["N3","C4","N4"],"allowed_bases":["C"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":false,"enabled":true,"notes":"Cytosine exocyclic amino valence angle. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"c_n3_c4_n4"},
  {"term_id":"c_c5_c4_n4","display_name":"C.C5-C4-N4","survey_group":"base_internal_angles","value_type":"linear_angle","unit":"deg","observation_level":"residue","source_atom_pattern":["C5","C4","N4"],"allowed_bases":["C"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":false,"enabled":true,"notes":"Cytosine exocyclic amino valence angle. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"c_c5_c4_n4"},
  {"term_id":"c_n1_c2_o2","display_name":"C.N1-C2-O2","survey_group":"base_internal_angles","value_type":"linear_angle","unit":"deg","observation_level":"residue","source_atom_pattern":["N1","C2","O2"],"allowed_bases":["C"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":false,"enabled":true,"notes":"Cytosine carbonyl-side valence angle. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"c_n1_c2_o2"},
  {"term_id":"c_n3_c2_o2","display_name":"C.N3-C2-O2","survey_group":"base_internal_angles","value_type":"linear_angle","unit":"deg","observation_level":"residue","source_atom_pattern":["N3","C2","O2"],"allowed_bases":["C"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":false,"enabled":true,"notes":"Cytosine carbonyl-side valence angle. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"c_n3_c2_o2"},
  {"term_id":"u_n1_c2_n3","display_name":"U.N1-C2-N3","survey_group":"base_internal_angles","value_type":"linear_angle","unit":"deg","observation_level":"residue","source_atom_pattern":["N1","C2","N3"],"allowed_bases":["U"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":false,"enabled":true,"notes":"Uracil six-member ring internal angle. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"t_n1_c2_n3"},
  {"term_id":"u_c2_n3_c4","display_name":"U.C2-N3-C4","survey_group":"base_internal_angles","value_type":"linear_angle","unit":"deg","observation_level":"residue","source_atom_pattern":["C2","N3","C4"],"allowed_bases":["U"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":false,"enabled":true,"notes":"Uracil six-member ring internal angle. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"t_c2_n3_c4"},
  {"term_id":"u_n3_c4_c5","display_name":"U.N3-C4-C5","survey_group":"base_internal_angles","value_type":"linear_angle","unit":"deg","observation_level":"residue","source_atom_pattern":["N3","C4","C5"],"allowed_bases":["U"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":false,"enabled":true,"notes":"Uracil six-member ring internal angle. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"t_n3_c4_c5"},
  {"term_id":"u_c4_c5_c6","display_name":"U.C4-C5-C6","survey_group":"base_internal_angles","value_type":"linear_angle","unit":"deg","observation_level":"residue","source_atom_pattern":["C4","C5","C6"],"allowed_bases":["U"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":false,"enabled":true,"notes":"Uracil six-member ring internal angle. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"t_c4_c5_c6"},
  {"term_id":"u_c5_c6_n1","display_name":"U.C5-C6-N1","survey_group":"base_internal_angles","value_type":"linear_angle","unit":"deg","observation_level":"residue","source_atom_pattern":["C5","C6","N1"],"allowed_bases":["U"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":false,"enabled":true,"notes":"Uracil six-member ring internal angle. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"t_c5_c6_n1"},
  {"term_id":"u_c6_n1_c2","display_name":"U.C6-N1-C2","survey_group":"base_internal_angles","value_type":"linear_angle","unit":"deg","observation_level":"residue","source_atom_pattern":["C6","N1","C2"],"allowed_bases":["U"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":false,"enabled":true,"notes":"Uracil six-member ring internal angle. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"t_c6_n1_c2"},
  {"term_id":"u_n3_c4_o4","display_name":"U.N3-C4-O4","survey_group":"base_internal_angles","value_type":"linear_angle","unit":"deg","observation_level":"residue","source_atom_pattern":["N3","C4","O4"],"allowed_bases":["U"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":false,"enabled":true,"notes":"Uracil O4 valence angle. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"t_n3_c4_o4"},
  {"term_id":"u_c5_c4_o4","display_name":"U.C5-C4-O4","survey_group":"base_internal_angles","value_type":"linear_angle","unit":"deg","observation_level":"residue","source_atom_pattern":["C5","C4","O4"],"allowed_bases":["U"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":false,"enabled":true,"notes":"Uracil O4 valence angle. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"t_c5_c4_o4"},
  {"term_id":"u_n1_c2_o2","display_name":"U.N1-C2-O2","survey_group":"base_internal_angles","value_type":"linear_angle","unit":"deg","observation_level":"residue","source_atom_pattern":["N1","C2","O2"],"allowed_bases":["U"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":false,"enabled":true,"notes":"Uracil O2 valence angle. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"t_n1_c2_o2"},
  {"term_id":"u_n3_c2_o2","display_name":"U.N3-C2-O2","survey_group":"base_internal_angles","value_type":"linear_angle","unit":"deg","observation_level":"residue","source_atom_pattern":["N3","C2","O2"],"allowed_bases":["U"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":false,"enabled":true,"notes":"Uracil O2 valence angle. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"t_n3_c2_o2"},
  {"term_id":"a_n1_c2_n3","display_name":"A.N1-C2-N3","survey_group":"base_internal_angles","value_type":"linear_angle","unit":"deg","observation_level":"residue","source_atom_pattern":["N1","C2","N3"],"allowed_bases":["A"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":false,"enabled":true,"notes":"Adenine six-member ring internal angle. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"a_n1_c2_n3"},
  {"term_id":"a_c2_n3_c4","display_name":"A.C2-N3-C4","survey_group":"base_internal_angles","value_type":"linear_angle","unit":"deg","observation_level":"residue","source_atom_pattern":["C2","N3","C4"],"allowed_bases":["A"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":false,"enabled":true,"notes":"Adenine six-member ring internal angle. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"a_c2_n3_c4"},
  {"term_id":"a_n3_c4_c5","display_name":"A.N3-C4-C5","survey_group":"base_internal_angles","value_type":"linear_angle","unit":"deg","observation_level":"residue","source_atom_pattern":["N3","C4","C5"],"allowed_bases":["A"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":false,"enabled":true,"notes":"Adenine six-member ring internal angle. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"a_n3_c4_c5"},
  {"term_id":"a_c4_c5_c6","display_name":"A.C4-C5-C6","survey_group":"base_internal_angles","value_type":"linear_angle","unit":"deg","observation_level":"residue","source_atom_pattern":["C4","C5","C6"],"allowed_bases":["A"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":false,"enabled":true,"notes":"Adenine six-member ring internal angle. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"a_c4_c5_c6"},
  {"term_id":"a_c5_c6_n1","display_name":"A.C5-C6-N1","survey_group":"base_internal_angles","value_type":"linear_angle","unit":"deg","observation_level":"residue","source_atom_pattern":["C5","C6","N1"],"allowed_bases":["A"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":false,"enabled":true,"notes":"Adenine six-member ring internal angle. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"a_c5_c6_n1"},
  {"term_id":"a_c6_n1_c2","display_name":"A.C6-N1-C2","survey_group":"base_internal_angles","value_type":"linear_angle","unit":"deg","observation_level":"residue","source_atom_pattern":["C6","N1","C2"],"allowed_bases":["A"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":false,"enabled":true,"notes":"Adenine six-member ring internal angle. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"a_c6_n1_c2"},
  {"term_id":"a_c4_c5_n7","display_name":"A.C4-C5-N7","survey_group":"base_internal_angles","value_type":"linear_angle","unit":"deg","observation_level":"residue","source_atom_pattern":["C4","C5","N7"],"allowed_bases":["A"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":false,"enabled":true,"notes":"Adenine five-member ring internal angle. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"a_c4_c5_n7"},
  {"term_id":"a_c5_n7_c8","display_name":"A.C5-N7-C8","survey_group":"base_internal_angles","value_type":"linear_angle","unit":"deg","observation_level":"residue","source_atom_pattern":["C5","N7","C8"],"allowed_bases":["A"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":false,"enabled":true,"notes":"Adenine five-member ring internal angle. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"a_c5_n7_c8"},
  {"term_id":"a_n7_c8_n9","display_name":"A.N7-C8-N9","survey_group":"base_internal_angles","value_type":"linear_angle","unit":"deg","observation_level":"residue","source_atom_pattern":["N7","C8","N9"],"allowed_bases":["A"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":false,"enabled":true,"notes":"Adenine five-member ring internal angle. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"a_n7_c8_n9"},
  {"term_id":"a_c8_n9_c4","display_name":"A.C8-N9-C4","survey_group":"base_internal_angles","value_type":"linear_angle","unit":"deg","observation_level":"residue","source_atom_pattern":["C8","N9","C4"],"allowed_bases":["A"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":false,"enabled":true,"notes":"Adenine five-member ring internal angle. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"a_c8_n9_c4"},
  {"term_id":"a_n9_c4_c5","display_name":"A.N9-C4-C5","survey_group":"base_internal_angles","value_type":"linear_angle","unit":"deg","observation_level":"residue","source_atom_pattern":["N9","C4","C5"],"allowed_bases":["A"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":false,"enabled":true,"notes":"Adenine five-member ring internal angle. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"a_n9_c4_c5"},
  {"term_id":"a_c5_c6_n6","display_name":"A.C5-C6-N6","survey_group":"base_internal_angles","value_type":"linear_angle","unit":"deg","observation_level":"residue","source_atom_pattern":["C5","C6","N6"],"allowed_bases":["A"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":false,"enabled":true,"notes":"Adenine exocyclic amino valence angle. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"a_c5_c6_n6"},
  {"term_id":"a_n1_c6_n6","display_name":"A.N1-C6-N6","survey_group":"base_internal_angles","value_type":"linear_angle","unit":"deg","observation_level":"residue","source_atom_pattern":["N1","C6","N6"],"allowed_bases":["A"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":false,"enabled":true,"notes":"Adenine exocyclic amino valence angle. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"a_n1_c6_n6"},
  {"term_id":"g_n1_c2_n3","display_name":"G.N1-C2-N3","survey_group":"base_internal_angles","value_type":"linear_angle","unit":"deg","observation_level":"residue","source_atom_pattern":["N1","C2","N3"],"allowed_bases":["G"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":false,"enabled":true,"notes":"Guanine six-member ring internal angle. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"g_n1_c2_n3"},
  {"term_id":"g_c2_n3_c4","display_name":"G.C2-N3-C4","survey_group":"base_internal_angles","value_type":"linear_angle","unit":"deg","observation_level":"residue","source_atom_pattern":["C2","N3","C4"],"allowed_bases":["G"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":false,"enabled":true,"notes":"Guanine six-member ring internal angle. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"g_c2_n3_c4"},
  {"term_id":"g_n3_c4_c5","display_name":"G.N3-C4-C5","survey_group":"base_internal_angles","value_type":"linear_angle","unit":"deg","observation_level":"residue","source_atom_pattern":["N3","C4","C5"],"allowed_bases":["G"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":false,"enabled":true,"notes":"Guanine six-member ring internal angle. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"g_n3_c4_c5"},
  {"term_id":"g_c4_c5_c6","display_name":"G.C4-C5-C6","survey_group":"base_internal_angles","value_type":"linear_angle","unit":"deg","observation_level":"residue","source_atom_pattern":["C4","C5","C6"],"allowed_bases":["G"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":false,"enabled":true,"notes":"Guanine six-member ring internal angle. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"g_c4_c5_c6"},
  {"term_id":"g_c5_c6_n1","display_name":"G.C5-C6-N1","survey_group":"base_internal_angles","value_type":"linear_angle","unit":"deg","observation_level":"residue","source_atom_pattern":["C5","C6","N1"],"allowed_bases":["G"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":false,"enabled":true,"notes":"Guanine six-member ring internal angle. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"g_c5_c6_n1"},
  {"term_id":"g_c6_n1_c2","display_name":"G.C6-N1-C2","survey_group":"base_internal_angles","value_type":"linear_angle","unit":"deg","observation_level":"residue","source_atom_pattern":["C6","N1","C2"],"allowed_bases":["G"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":false,"enabled":true,"notes":"Guanine six-member ring internal angle. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"g_c6_n1_c2"},
  {"term_id":"g_c4_c5_n7","display_name":"G.C4-C5-N7","survey_group":"base_internal_angles","value_type":"linear_angle","unit":"deg","observation_level":"residue","source_atom_pattern":["C4","C5","N7"],"allowed_bases":["G"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":false,"enabled":true,"notes":"Guanine five-member ring internal angle. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"g_c4_c5_n7"},
  {"term_id":"g_c5_n7_c8","display_name":"G.C5-N7-C8","survey_group":"base_internal_angles","value_type":"linear_angle","unit":"deg","observation_level":"residue","source_atom_pattern":["C5","N7","C8"],"allowed_bases":["G"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":false,"enabled":true,"notes":"Guanine five-member ring internal angle. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"g_c5_n7_c8"},
  {"term_id":"g_n7_c8_n9","display_name":"G.N7-C8-N9","survey_group":"base_internal_angles","value_type":"linear_angle","unit":"deg","observation_level":"residue","source_atom_pattern":["N7","C8","N9"],"allowed_bases":["G"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":false,"enabled":true,"notes":"Guanine five-member ring internal angle. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"g_n7_c8_n9"},
  {"term_id":"g_c8_n9_c4","display_name":"G.C8-N9-C4","survey_group":"base_internal_angles","value_type":"linear_angle","unit":"deg","observation_level":"residue","source_atom_pattern":["C8","N9","C4"],"allowed_bases":["G"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":false,"enabled":true,"notes":"Guanine five-member ring internal angle. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"g_c8_n9_c4"},
  {"term_id":"g_n9_c4_c5","display_name":"G.N9-C4-C5","survey_group":"base_internal_angles","value_type":"linear_angle","unit":"deg","observation_level":"residue","source_atom_pattern":["N9","C4","C5"],"allowed_bases":["G"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":false,"enabled":true,"notes":"Guanine five-member ring internal angle. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"g_n9_c4_c5"},
  {"term_id":"g_n1_c2_n2","display_name":"G.N1-C2-N2","survey_group":"base_internal_angles","value_type":"linear_angle","unit":"deg","observation_level":"residue","source_atom_pattern":["N1","C2","N2"],"allowed_bases":["G"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":false,"enabled":true,"notes":"Guanine exocyclic amino valence angle. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"g_n1_c2_n2"},
  {"term_id":"g_n3_c2_n2","display_name":"G.N3-C2-N2","survey_group":"base_internal_angles","value_type":"linear_angle","unit":"deg","observation_level":"residue","source_atom_pattern":["N3","C2","N2"],"allowed_bases":["G"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":false,"enabled":true,"notes":"Guanine exocyclic amino valence angle. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"g_n3_c2_n2"},
  {"term_id":"g_c5_c6_o6","display_name":"G.C5-C6-O6","survey_group":"base_internal_angles","value_type":"linear_angle","unit":"deg","observation_level":"residue","source_atom_pattern":["C5","C6","O6"],"allowed_bases":["G"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":false,"enabled":true,"notes":"Guanine O6 valence angle. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"g_c5_c6_o6"},
  {"term_id":"g_n1_c6_o6","display_name":"G.N1-C6-O6","survey_group":"base_internal_angles","value_type":"linear_angle","unit":"deg","observation_level":"residue","source_atom_pattern":["N1","C6","O6"],"allowed_bases":["G"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":false,"enabled":true,"notes":"Guanine O6 valence angle. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"g_n1_c6_o6"},
  {"term_id":"c_n1_c2_n3_c4","display_name":"C.N1-C2-N3-C4","survey_group":"base_local_dihedrals","value_type":"dihedral","unit":"deg","observation_level":"residue","source_atom_pattern":["N1","C2","N3","C4"],"allowed_bases":["C"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":true,"enabled":true,"notes":"Cytosine ring-planarity torsion. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"c_n1_c2_n3_c4"},
  {"term_id":"c_c2_n3_c4_c5","display_name":"C.C2-N3-C4-C5","survey_group":"base_local_dihedrals","value_type":"dihedral","unit":"deg","observation_level":"residue","source_atom_pattern":["C2","N3","C4","C5"],"allowed_bases":["C"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":true,"enabled":true,"notes":"Cytosine ring-planarity torsion. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"c_c2_n3_c4_c5"},
  {"term_id":"c_n3_c4_c5_c6","display_name":"C.N3-C4-C5-C6","survey_group":"base_local_dihedrals","value_type":"dihedral","unit":"deg","observation_level":"residue","source_atom_pattern":["N3","C4","C5","C6"],"allowed_bases":["C"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":true,"enabled":true,"notes":"Cytosine ring-planarity torsion. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"c_n3_c4_c5_c6"},
  {"term_id":"c_c4_c5_c6_n1","display_name":"C.C4-C5-C6-N1","survey_group":"base_local_dihedrals","value_type":"dihedral","unit":"deg","observation_level":"residue","source_atom_pattern":["C4","C5","C6","N1"],"allowed_bases":["C"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":true,"enabled":true,"notes":"Cytosine ring-planarity torsion. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"c_c4_c5_c6_n1"},
  {"term_id":"c_c5_c6_n1_c2","display_name":"C.C5-C6-N1-C2","survey_group":"base_local_dihedrals","value_type":"dihedral","unit":"deg","observation_level":"residue","source_atom_pattern":["C5","C6","N1","C2"],"allowed_bases":["C"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":true,"enabled":true,"notes":"Cytosine ring-planarity torsion. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"c_c5_c6_n1_c2"},
  {"term_id":"c_c6_n1_c2_n3","display_name":"C.C6-N1-C2-N3","survey_group":"base_local_dihedrals","value_type":"dihedral","unit":"deg","observation_level":"residue","source_atom_pattern":["C6","N1","C2","N3"],"allowed_bases":["C"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":true,"enabled":true,"notes":"Cytosine ring-planarity torsion. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"c_c6_n1_c2_n3"},
  {"term_id":"c_c2_n3_c4_n4","display_name":"C.C2-N3-C4-N4","survey_group":"base_local_dihedrals","value_type":"dihedral","unit":"deg","observation_level":"residue","source_atom_pattern":["C2","N3","C4","N4"],"allowed_bases":["C"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":true,"enabled":true,"notes":"Cytosine N4 heavy-atom out-of-plane proxy. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"c_c2_n3_c4_n4"},
  {"term_id":"c_c6_c5_c4_n4","display_name":"C.C6-C5-C4-N4","survey_group":"base_local_dihedrals","value_type":"dihedral","unit":"deg","observation_level":"residue","source_atom_pattern":["C6","C5","C4","N4"],"allowed_bases":["C"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":true,"enabled":true,"notes":"Cytosine N4 heavy-atom out-of-plane proxy. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"c_c6_c5_c4_n4"},
  {"term_id":"c_c4_n3_c2_o2","display_name":"C.C4-N3-C2-O2","survey_group":"base_local_dihedrals","value_type":"dihedral","unit":"deg","observation_level":"residue","source_atom_pattern":["C4","N3","C2","O2"],"allowed_bases":["C"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":true,"enabled":true,"notes":"Cytosine O2 heavy-atom out-of-plane proxy. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"c_c4_n3_c2_o2"},
  {"term_id":"c_c6_n1_c2_o2","display_name":"C.C6-N1-C2-O2","survey_group":"base_local_dihedrals","value_type":"dihedral","unit":"deg","observation_level":"residue","source_atom_pattern":["C6","N1","C2","O2"],"allowed_bases":["C"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":true,"enabled":true,"notes":"Cytosine O2 heavy-atom out-of-plane proxy. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"c_c6_n1_c2_o2"},
  {"term_id":"u_n1_c2_n3_c4","display_name":"U.N1-C2-N3-C4","survey_group":"base_local_dihedrals","value_type":"dihedral","unit":"deg","observation_level":"residue","source_atom_pattern":["N1","C2","N3","C4"],"allowed_bases":["U"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":true,"enabled":true,"notes":"Uracil ring-planarity torsion. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"t_n1_c2_n3_c4"},
  {"term_id":"u_c2_n3_c4_c5","display_name":"U.C2-N3-C4-C5","survey_group":"base_local_dihedrals","value_type":"dihedral","unit":"deg","observation_level":"residue","source_atom_pattern":["C2","N3","C4","C5"],"allowed_bases":["U"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":true,"enabled":true,"notes":"Uracil ring-planarity torsion. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"t_c2_n3_c4_c5"},
  {"term_id":"u_n3_c4_c5_c6","display_name":"U.N3-C4-C5-C6","survey_group":"base_local_dihedrals","value_type":"dihedral","unit":"deg","observation_level":"residue","source_atom_pattern":["N3","C4","C5","C6"],"allowed_bases":["U"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":true,"enabled":true,"notes":"Uracil ring-planarity torsion. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"t_n3_c4_c5_c6"},
  {"term_id":"u_c4_c5_c6_n1","display_name":"U.C4-C5-C6-N1","survey_group":"base_local_dihedrals","value_type":"dihedral","unit":"deg","observation_level":"residue","source_atom_pattern":["C4","C5","C6","N1"],"allowed_bases":["U"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":true,"enabled":true,"notes":"Uracil ring-planarity torsion. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"t_c4_c5_c6_n1"},
  {"term_id":"u_c5_c6_n1_c2","display_name":"U.C5-C6-N1-C2","survey_group":"base_local_dihedrals","value_type":"dihedral","unit":"deg","observation_level":"residue","source_atom_pattern":["C5","C6","N1","C2"],"allowed_bases":["U"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":true,"enabled":true,"notes":"Uracil ring-planarity torsion. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"t_c5_c6_n1_c2"},
  {"term_id":"u_c6_n1_c2_n3","display_name":"U.C6-N1-C2-N3","survey_group":"base_local_dihedrals","value_type":"dihedral","unit":"deg","observation_level":"residue","source_atom_pattern":["C6","N1","C2","N3"],"allowed_bases":["U"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":true,"enabled":true,"notes":"Uracil ring-planarity torsion. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"t_c6_n1_c2_n3"},
  {"term_id":"u_c2_n3_c4_o4","display_name":"U.C2-N3-C4-O4","survey_group":"base_local_dihedrals","value_type":"dihedral","unit":"deg","observation_level":"residue","source_atom_pattern":["C2","N3","C4","O4"],"allowed_bases":["U"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":true,"enabled":true,"notes":"Uracil O4 heavy-atom out-of-plane proxy. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"t_c2_n3_c4_o4"},
  {"term_id":"u_c6_c5_c4_o4","display_name":"U.C6-C5-C4-O4","survey_group":"base_local_dihedrals","value_type":"dihedral","unit":"deg","observation_level":"residue","source_atom_pattern":["C6","C5","C4","O4"],"allowed_bases":["U"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":true,"enabled":true,"notes":"Uracil O4 heavy-atom out-of-plane proxy. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"t_c6_c5_c4_o4"},
  {"term_id":"u_c4_n3_c2_o2","display_name":"U.C4-N3-C2-O2","survey_group":"base_local_dihedrals","value_type":"dihedral","unit":"deg","observation_level":"residue","source_atom_pattern":["C4","N3","C2","O2"],"allowed_bases":["U"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":true,"enabled":true,"notes":"Uracil O2 heavy-atom out-of-plane proxy. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"t_c4_n3_c2_o2"},
  {"term_id":"u_c6_n1_c2_o2","display_name":"U.C6-N1-C2-O2","survey_group":"base_local_dihedrals","value_type":"dihedral","unit":"deg","observation_level":"residue","source_atom_pattern":["C6","N1","C2","O2"],"allowed_bases":["U"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":true,"enabled":true,"notes":"Uracil O2 heavy-atom out-of-plane proxy. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"t_c6_n1_c2_o2"},
  {"term_id":"a_n1_c2_n3_c4","display_name":"A.N1-C2-N3-C4","survey_group":"base_local_dihedrals","value_type":"dihedral","unit":"deg","observation_level":"residue","source_atom_pattern":["N1","C2","N3","C4"],"allowed_bases":["A"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":true,"enabled":true,"notes":"Adenine six-member-ring planarity torsion. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"a_n1_c2_n3_c4"},
  {"term_id":"a_c2_n3_c4_c5","display_name":"A.C2-N3-C4-C5","survey_group":"base_local_dihedrals","value_type":"dihedral","unit":"deg","observation_level":"residue","source_atom_pattern":["C2","N3","C4","C5"],"allowed_bases":["A"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":true,"enabled":true,"notes":"Adenine six-member-ring planarity torsion. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"a_c2_n3_c4_c5"},
  {"term_id":"a_n3_c4_c5_c6","display_name":"A.N3-C4-C5-C6","survey_group":"base_local_dihedrals","value_type":"dihedral","unit":"deg","observation_level":"residue","source_atom_pattern":["N3","C4","C5","C6"],"allowed_bases":["A"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":true,"enabled":true,"notes":"Adenine six-member-ring planarity torsion. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"a_n3_c4_c5_c6"},
  {"term_id":"a_c4_c5_c6_n1","display_name":"A.C4-C5-C6-N1","survey_group":"base_local_dihedrals","value_type":"dihedral","unit":"deg","observation_level":"residue","source_atom_pattern":["C4","C5","C6","N1"],"allowed_bases":["A"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":true,"enabled":true,"notes":"Adenine six-member-ring planarity torsion. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"a_c4_c5_c6_n1"},
  {"term_id":"a_c5_c6_n1_c2","display_name":"A.C5-C6-N1-C2","survey_group":"base_local_dihedrals","value_type":"dihedral","unit":"deg","observation_level":"residue","source_atom_pattern":["C5","C6","N1","C2"],"allowed_bases":["A"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":true,"enabled":true,"notes":"Adenine six-member-ring planarity torsion. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"a_c5_c6_n1_c2"},
  {"term_id":"a_c6_n1_c2_n3","display_name":"A.C6-N1-C2-N3","survey_group":"base_local_dihedrals","value_type":"dihedral","unit":"deg","observation_level":"residue","source_atom_pattern":["C6","N1","C2","N3"],"allowed_bases":["A"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":true,"enabled":true,"notes":"Adenine six-member-ring planarity torsion. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"a_c6_n1_c2_n3"},
  {"term_id":"a_c4_c5_n7_c8","display_name":"A.C4-C5-N7-C8","survey_group":"base_local_dihedrals","value_type":"dihedral","unit":"deg","observation_level":"residue","source_atom_pattern":["C4","C5","N7","C8"],"allowed_bases":["A"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":true,"enabled":true,"notes":"Adenine five-member-ring planarity torsion. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"a_c4_c5_n7_c8"},
  {"term_id":"a_c5_n7_c8_n9","display_name":"A.C5-N7-C8-N9","survey_group":"base_local_dihedrals","value_type":"dihedral","unit":"deg","observation_level":"residue","source_atom_pattern":["C5","N7","C8","N9"],"allowed_bases":["A"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":true,"enabled":true,"notes":"Adenine five-member-ring planarity torsion. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"a_c5_n7_c8_n9"},
  {"term_id":"a_n7_c8_n9_c4","display_name":"A.N7-C8-N9-C4","survey_group":"base_local_dihedrals","value_type":"dihedral","unit":"deg","observation_level":"residue","source_atom_pattern":["N7","C8","N9","C4"],"allowed_bases":["A"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":true,"enabled":true,"notes":"Adenine five-member-ring planarity torsion. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"a_n7_c8_n9_c4"},
  {"term_id":"a_c8_n9_c4_c5","display_name":"A.C8-N9-C4-C5","survey_group":"base_local_dihedrals","value_type":"dihedral","unit":"deg","observation_level":"residue","source_atom_pattern":["C8","N9","C4","C5"],"allowed_bases":["A"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":true,"enabled":true,"notes":"Adenine five-member-ring planarity torsion. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"a_c8_n9_c4_c5"},
  {"term_id":"a_n9_c4_c5_n7","display_name":"A.N9-C4-C5-N7","survey_group":"base_local_dihedrals","value_type":"dihedral","unit":"deg","observation_level":"residue","source_atom_pattern":["N9","C4","C5","N7"],"allowed_bases":["A"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":true,"enabled":true,"notes":"Adenine five-member-ring planarity torsion. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"a_n9_c4_c5_n7"},
  {"term_id":"a_n1_c6_c5_n6","display_name":"A.N1-C6-C5-N6","survey_group":"base_local_dihedrals","value_type":"dihedral","unit":"deg","observation_level":"residue","source_atom_pattern":["N1","C6","C5","N6"],"allowed_bases":["A"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":true,"enabled":true,"notes":"Adenine N6 heavy-atom out-of-plane proxy. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"a_n1_c6_c5_n6"},
  {"term_id":"a_n3_c4_c5_n6","display_name":"A.N3-C4-C5-N6","survey_group":"base_local_dihedrals","value_type":"dihedral","unit":"deg","observation_level":"residue","source_atom_pattern":["N3","C4","C5","N6"],"allowed_bases":["A"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":true,"enabled":true,"notes":"Adenine N6 heavy-atom out-of-plane proxy. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"a_n3_c4_c5_n6"},
  {"term_id":"g_n1_c2_n3_c4","display_name":"G.N1-C2-N3-C4","survey_group":"base_local_dihedrals","value_type":"dihedral","unit":"deg","observation_level":"residue","source_atom_pattern":["N1","C2","N3","C4"],"allowed_bases":["G"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":true,"enabled":true,"notes":"Guanine six-member-ring planarity torsion. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"g_n1_c2_n3_c4"},
  {"term_id":"g_c2_n3_c4_c5","display_name":"G.C2-N3-C4-C5","survey_group":"base_local_dihedrals","value_type":"dihedral","unit":"deg","observation_level":"residue","source_atom_pattern":["C2","N3","C4","C5"],"allowed_bases":["G"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":true,"enabled":true,"notes":"Guanine six-member-ring planarity torsion. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"g_c2_n3_c4_c5"},
  {"term_id":"g_n3_c4_c5_c6","display_name":"G.N3-C4-C5-C6","survey_group":"base_local_dihedrals","value_type":"dihedral","unit":"deg","observation_level":"residue","source_atom_pattern":["N3","C4","C5","C6"],"allowed_bases":["G"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":true,"enabled":true,"notes":"Guanine six-member-ring planarity torsion. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"g_n3_c4_c5_c6"},
  {"term_id":"g_c4_c5_c6_n1","display_name":"G.C4-C5-C6-N1","survey_group":"base_local_dihedrals","value_type":"dihedral","unit":"deg","observation_level":"residue","source_atom_pattern":["C4","C5","C6","N1"],"allowed_bases":["G"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":true,"enabled":true,"notes":"Guanine six-member-ring planarity torsion. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"g_c4_c5_c6_n1"},
  {"term_id":"g_c5_c6_n1_c2","display_name":"G.C5-C6-N1-C2","survey_group":"base_local_dihedrals","value_type":"dihedral","unit":"deg","observation_level":"residue","source_atom_pattern":["C5","C6","N1","C2"],"allowed_bases":["G"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":true,"enabled":true,"notes":"Guanine six-member-ring planarity torsion. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"g_c5_c6_n1_c2"},
  {"term_id":"g_c6_n1_c2_n3","display_name":"G.C6-N1-C2-N3","survey_group":"base_local_dihedrals","value_type":"dihedral","unit":"deg","observation_level":"residue","source_atom_pattern":["C6","N1","C2","N3"],"allowed_bases":["G"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":true,"enabled":true,"notes":"Guanine six-member-ring planarity torsion. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"g_c6_n1_c2_n3"},
  {"term_id":"g_c4_c5_n7_c8","display_name":"G.C4-C5-N7-C8","survey_group":"base_local_dihedrals","value_type":"dihedral","unit":"deg","observation_level":"residue","source_atom_pattern":["C4","C5","N7","C8"],"allowed_bases":["G"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":true,"enabled":true,"notes":"Guanine five-member-ring planarity torsion. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"g_c4_c5_n7_c8"},
  {"term_id":"g_c5_n7_c8_n9","display_name":"G.C5-N7-C8-N9","survey_group":"base_local_dihedrals","value_type":"dihedral","unit":"deg","observation_level":"residue","source_atom_pattern":["C5","N7","C8","N9"],"allowed_bases":["G"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":true,"enabled":true,"notes":"Guanine five-member-ring planarity torsion. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"g_c5_n7_c8_n9"},
  {"term_id":"g_n7_c8_n9_c4","display_name":"G.N7-C8-N9-C4","survey_group":"base_local_dihedrals","value_type":"dihedral","unit":"deg","observation_level":"residue","source_atom_pattern":["N7","C8","N9","C4"],"allowed_bases":["G"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":true,"enabled":true,"notes":"Guanine five-member-ring planarity torsion. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"g_n7_c8_n9_c4"},
  {"term_id":"g_c8_n9_c4_c5","display_name":"G.C8-N9-C4-C5","survey_group":"base_local_dihedrals","value_type":"dihedral","unit":"deg","observation_level":"residue","source_atom_pattern":["C8","N9","C4","C5"],"allowed_bases":["G"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":true,"enabled":true,"notes":"Guanine five-member-ring planarity torsion. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"g_c8_n9_c4_c5"},
  {"term_id":"g_n9_c4_c5_n7","display_name":"G.N9-C4-C5-N7","survey_group":"base_local_dihedrals","value_type":"dihedral","unit":"deg","observation_level":"residue","source_atom_pattern":["N9","C4","C5","N7"],"allowed_bases":["G"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":true,"enabled":true,"notes":"Guanine five-member-ring planarity torsion. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"g_n9_c4_c5_n7"},
  {"term_id":"g_n1_c2_n3_n2","display_name":"G.N1-C2-N3-N2","survey_group":"base_local_dihedrals","value_type":"dihedral","unit":"deg","observation_level":"residue","source_atom_pattern":["N1","C2","N3","N2"],"allowed_bases":["G"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":true,"enabled":true,"notes":"Guanine N2 heavy-atom out-of-plane proxy. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"g_n1_c2_n3_n2"},
  {"term_id":"g_c4_n3_c2_n2","display_name":"G.C4-N3-C2-N2","survey_group":"base_local_dihedrals","value_type":"dihedral","unit":"deg","observation_level":"residue","source_atom_pattern":["C4","N3","C2","N2"],"allowed_bases":["G"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":true,"enabled":true,"notes":"Guanine N2 heavy-atom out-of-plane proxy. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"g_c4_n3_c2_n2"},
  {"term_id":"g_n1_c6_c5_o6","display_name":"G.N1-C6-C5-O6","survey_group":"base_local_dihedrals","value_type":"dihedral","unit":"deg","observation_level":"residue","source_atom_pattern":["N1","C6","C5","O6"],"allowed_bases":["G"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":true,"enabled":true,"notes":"Guanine O6 heavy-atom out-of-plane proxy. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"g_n1_c6_c5_o6"},
  {"term_id":"g_n3_c4_c5_o6","display_name":"G.N3-C4-C5-O6","survey_group":"base_local_dihedrals","value_type":"dihedral","unit":"deg","observation_level":"residue","source_atom_pattern":["N3","C4","C5","O6"],"allowed_bases":["G"],"allowed_pair_types":[],"requires_pair":false,"requires_step":false,"opening_binnable":true,"is_circular":true,"enabled":true,"notes":"Guanine O6 heavy-atom out-of-plane proxy. Independent of pairing; opening grouping requires an explicit interaction join.","source_term_id":"g_n3_c4_c5_o6"},
  {"term_id":"same_pair_g_c6__c_n4","display_name":"same_pair:G.C6--C.N4","survey_group":"major_groove_distances","value_type":"distance","unit":"A","observation_level":"pair","source_atom_pattern":["G.C6","C.N4"],"allowed_bases":["G","C"],"allowed_pair_types":["G-C","C-G"],"requires_pair":true,"requires_step":false,"opening_binnable":true,"is_circular":false,"enabled":true,"notes":"Same-pair G.C6 to C.N4 distance for GC-like pairs.","source_term_id":"same_pair_g_c6__c_n4"},
  {"term_id":"same_pair_a_n6__u_o4","display_name":"same_pair:A.N6--U.O4","survey_group":"major_groove_distances","value_type":"distance","unit":"A","observation_level":"pair","source_atom_pattern":["A.N6","U.O4"],"allowed_bases":["A","U"],"allowed_pair_types":["A-U","U-A"],"requires_pair":true,"requires_step":false,"opening_binnable":true,"is_circular":false,"enabled":true,"notes":"Same-pair A.N6 to U.O4 distance for AU-like pairs.","source_term_id":"same_pair_a_n6__t_o4"}
]);

// Retained DNA display bins are descriptive UI defaults, not RNA quality thresholds.
export const OPENING_BINS = freezeDeep([
  {
    "id": "small",
    "label": "Small opening",
    "min": -16,
    "max": -8,
    "include_min": true,
    "include_max": false,
    "notes": "Opening in [-16, -8) degrees."
  },
  {
    "id": "middle",
    "label": "Middle opening",
    "min": -8,
    "max": 2,
    "include_min": true,
    "include_max": false,
    "notes": "Opening in [-8, 2) degrees."
  },
  {
    "id": "large",
    "label": "Large opening",
    "min": 2,
    "max": 10,
    "include_min": true,
    "include_max": true,
    "notes": "Opening in [2, 10] degrees."
  },
  {
    "id": "outside",
    "label": "Outside bins",
    "min": null,
    "max": null,
    "include_min": false,
    "include_max": false,
    "notes": "Finite opening outside the small, middle, and large bins."
  },
  {
    "id": "missing",
    "label": "Missing opening",
    "min": null,
    "max": null,
    "include_min": false,
    "include_max": false,
    "notes": "No finite opening value is available."
  }
]);
export const LOCAL_FRAME_RECIPES = freezeDeep([{frame_id:'rna_standard_base', display_name:'RNA standard base frame', anchor_bases:['A','C','G','U'], source:'x3DNA Atomic_A/C/G/U.pdb'}, {frame_id:'cytosine_standard_pair', display_name:'Cytosine standard frame (CG pair)', anchor_bases:['C'], sequence_contexts:['C-G','G-C'], source:'x3DNA Atomic_C.pdb', notes:'Standard base frame; not the DNA N1-C2 plane recipe.'}]);
export function enabledScalarTerms() { return TERM_REGISTRY.filter(term => term.enabled); }
export function publicTermRegistry() { return structuredClone(TERM_REGISTRY); }
export function publicBaseGeometryConfig() { return structuredClone({terms:TERM_REGISTRY, base_atoms:BASE_ATOMS, opening_bins:OPENING_BINS, local_frame_recipes:LOCAL_FRAME_RECIPES}); }
export function openingBinForValue(value, bins=OPENING_BINS) {
  if (!Number.isFinite(value)) return 'missing';
  for (const bin of bins) {
    if (bin.min == null || bin.max == null) continue;
    if ((bin.include_min ? value >= bin.min : value > bin.min) && (bin.include_max ? value <= bin.max : value < bin.max)) return bin.id;
  }
  return 'outside';
}
