/** Display names from the archived NAKBnadict.js dictionary; scientific scope stays in metadata. */
const NAKB_NAMES = {
  "function": "function",
  "makesprotein": "protein synthesis",
  "ribosomalrna": "ribosomal RNA",
  "trna": "transfer RNA",
  "codingrna": "messenger RNA (mRNA)",
  "translatemod": "translation regulating",
  "tmrna": "transfer-messenger (tmRNA)",
  "rnaires": "IRES element",
  "frameshift": "frameshifting element",
  "srprna": "SRP RNA",
  "replication": "replication regulating",
  "transcription": "transcription regulating",
  "antiterminator": "antitermination element",
  "riboswitch": "riboswitch",
  "aaswitch": "amino-acid riboswitch",
  "abswitch": "antibiotic riboswitch",
  "ionswitch": "ion riboswitch",
  "purineswitch": "purine-compound riboswitch",
  "tboxswitch": "tRNA riboswitch",
  "vitaminswitch": "enzyme cofactor riboswitch",
  "aptamer": "aptamer",
  "fluoroaptamer": "fluorescing aptamer",
  "thrombinaptamer": "thrombin responsive aptamer",
  "natransfactor": "trans-acting transcriptional regulator",
  "hivtar": "activation response element",
  "7sksnrna": "7SK RNA",
  "posttranscription": "post-transcriptional processing",
  "snrna": "small nuclear RNA (snRNA)",
  "snorna": "small nucleolar RNA (snoRNA)",
  "cellsorting": "cellular localization element",
  "altsplice": "alternative splicing element",
  "nazyme": "catalytic",
  "group1intron": "group I intron ribozyme",
  "group2intron": "group II intron ribozyme",
  "glmsribozyme": "glmS ribozyme",
  "vsribozyme": "Varkud satellite ribozyme",
  "ribonucleasep": "ribonuclease P ribozyme",
  "hairpin": "hairpin ribozyme",
  "hammerhead": "hammerhead ribozyme",
  "hdvribozyme": "Hepatitis delta virus ribozyme",
  "selfreplicating": "self-replicating",
  "virusna": "virus NA",
  "telomere": "telomeric DNA",
  "telomerase": "telomerase RNA",
  "otherna": "other/unknown",
  "olerna": "OLE RNA",
  "arrpofrna": "ARRPOF RNA",
  "roolrna": "ROOL RNA",
  "golldrna": "GOLLD RNA",
  "raiarna": "raiA RNA",
  "nastructure": "structure",
  "double": "double helix",
  "aform": "A-form double helix",
  "bform": "B-form double helix",
  "zform": "Z-form double helix",
  "parallel": "parallel helix",
  "imotif": "I-motif",
  "triple": "triple helix",
  "quadruplex": "quadruplex",
  "multiplex": "multiplex",
  "holliday": "Holliday junction",
  "feature": "feature",
  "founding": "founding structure",
  "dodecamer": "DNA dodecamer",
  "cyclic": "cyclic",
  "bulge": "bulge",
  "mispair": "mispair",
  "mispairaa": "A-A mispair",
  "mispairac": "A-C mispair",
  "mispairag": "A-G mispair",
  "mispaircc": "C-C mispair",
  "mispairct": "C-T mispair",
  "mispairgg": "G-G mispair",
  "mispairgt": "G-T mispair",
  "mispairtt": "T-T mispair",
  "kinkturn": "kink turn",
  "tetraloop": "tetraloop",
  "ornate": "Ornate RNA",
  "ornatemulti": "Multimeric Ornate RNA",
  "designed": "designed assembly"
};
export const annotationLabel = value => NAKB_NAMES[value] || String(value).replaceAll("_", " ");
